version: '2'
services:
  flask:
    build: docker-flask-fastapi
    restart: always
    ports:
      - "127.0.0.1:9191:9191"
      - "127.0.0.1:5000:5000"
    volumes:
      - ../..:/octo-deco
      - ./scripts:/scripts
    mem_limit: 500m
    command: "/bin/sh -c '/scripts/run_uwsgi_ini.dev.sh'"
  fastapi_db:
    build: docker-flask-fastapi
    restart: always
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - ../..:/octo-deco
      - ../../instance:/flask_instance
      - ./scripts:/scripts
    mem_limit: 100m
    command: "/bin/sh -c '/scripts/run_uvicorn.dev.sh'"
